### PR TITLE
Fix http payload

### PR DESCRIPTION
**Pull request by xadh00m**
The issue seems to be fixed by using the first element in the buffer.

I´ve also updated several dependencies. But I did not update the following ones because they broke the tests.
```
"commander" can be updated from ~2.3.0 to ~2.8.0 (Installed: 2.3.0, Latest: 2.8.0)
"mqtt" can be updated from ~0.3.11 to ~1.1.3 (Installed: 0.3.13, Latest: 1.1.3)
"coap" can be updated from ~0.8.0 to ~0.10.2 (Installed: 0.8.0, Latest: 0.10.2)
"st" can be updated from ~0.5.1 to ~0.5.3 (Installed: 0.5.3, Latest: 0.5.3)
```
Using the latest *mqtt* module would make *mows* obsolete but I did not have the time to dig into the API changes and fix the test.

### CODE REVIEW

**Comment by xadh00m** [comment]
I´ve updated my Ecplise account and signed the CLA. Do I need to do something else to let the checks pass?

**Comment by mcollina** [comment]
You should do a commit with `git commit -s`, so that it is signed with your email address. See https://git.eclipse.org/r/Documentation/user-signedoffby.html#Signed-off-by

**Comment by xadh00m** [comment]
I´ve signed the last commit. My eclipse account credentials match the signed off details. Any idea what might be the issue here?

**Comment by mcollina** [comment]
I spoke with the lads, all commits must be signed off.

The easy way is to squash all of them into one, and sign off that one.

**Pull request closed without merging**
