### PR TITLE
Binary HTTP Payloads, HTTP Webhooks and Node 0.12

### PR DESCRIPTION
**Pull request by psorowka**
This is a rather full PR. I think you should cherry pick the commits for the upstream branch. Especially the webhook feature is not yet complete, it is especially missing persistence.

The other things are quite nice:

--> I had found that HTTP PUT would not deal correctly with binary payloads (yet). This is now fixed
--> I have updated all dependencies and tests so that ponte now runs on node 0.12

### CODE REVIEW

**Comment by psorowka** [comment]
oh wait. Travis is failing on `should allow a client to publish and subscribe
    with the serve libraries option
    without the serve libraries option`. Locally it was fine. I'll look into it

**Comment by psorowka** [comment]
All that was based on an outdated version of ponte. Closing for now, have to sort myself..

**Comment by mcollina** [comment]
Can we get a PR about webhooks?

**Comment by psorowka** [comment]
Sure but I would like to consolidate the persistence of subscriptions first. I'll PR as soon as I feel ready for it!

**Comment by psorowka** [comment]
Hi @mcollina sorry for not commenting on this for so long. I have decided to drop the webhook support in ponte again for our platform because it doesn't feel right to have this in the broker. Offering such an API throws up a bunch of other questions and implications, which would essentially push ponte away from being a pure broker to a more full-stack platform. Even if this is what we want, the webhooks feel not as the right entry point. Before, something like a user management would be needed (== who is allowed to create webhooks?)
We for ourselves have introduced node red  which is a way more natural way of forwarding messages to a HTTP endpoint.

**Pull request closed without merging**
