### PR TITLE
Bumped dependencies, added Node4 to travis

### PR DESCRIPTION
**Pull request by psorowka**
Signed-off-by: Peter Sorowka <sorowka@skybus.io>

### CODE REVIEW

**Comment by psorowka** [comment]
@mcollina could you accept or comment on this PR?

**Comment by mcollina** [comment]
Dependencies do not (fully) support node v4+. Ascoltatori is the most critical, see https://github.com/mcollina/ascoltatori/pull/137.

**Comment by psorowka** [comment]
Ok, just waiting for mosca@1.0.0 and ascoltatori@2.0.0 to be released - ready for ponte@1.0.0 running on node4 then!

**Comment by psorowka** [comment]
hu, we don't have travis in place here? build results here: https://travis-ci.org/cybusio/ponte/builds/103225309

**Comment by psorowka** [comment]
Build is green: https://travis-ci.org/cybusio/ponte/builds/103336412

READY TO MERGE :)

**Comment by psorowka** [comment]
yeeha :)

**Pull request merged**
