### PR TITLE
Node v6.9.5 refactoring and new code formatting

### PR DESCRIPTION
**Pull request by chombium**
Refactoring and dependencies upgrades to enable Ponte run on the latest LTS version of Node v. 6.9.5.

Fixes for:
1. Update Ponte so that it runs on the latest Node LTS version #28
2. Add better check style and code formatting #29
3. Document the source code with JSDoc #30
4. nsp check reports security vulnerabilities related to mosca 1.1.3 #34

### CODE REVIEW

**Comment by mcollina** [comment]
👍 for me.

Given the size of this contribution, should this be checked by legal? cc @kartben

**Comment by kartben** [comment]
@mcollina is correct - i just opened a CQ so as our IP team reviews the contribution. Once they will give a GO this can be merged. Thanks @chombium

**Comment by chombium** [comment]
Hi @kartben,

any news from the IP Team?

**Comment by kartben** [comment]
Hey @chombium and @mcollina - sorry it took so long. The pull request has been reviewed and approved by our IP Team. 
@mcollina can you merge it and proceed with nominating Jovan as a committer on Ponte (see https://www.eclipse.org/projects/handbook/#elections-committer, it should take just a minute of your time :-))

**Comment by mcollina** [comment]
It should be done

**Comment by chombium** [comment]
Hi @kartben,

now when the changes have been merged and the voting is finished. Should we do something more so that I can get the commit rights?

what does the following mean?
"The next step is for the project lead to return to the portal and fill in the
VCS package and employer information for Jovan Kostovski."

Should @mcollina  do something more?
BTW. My employer has nothing to do with Ponte. I am contributing to Ponte in my free time.

Best Regards,
Jovan

**Pull request merged**
